"""Add tasks table

Revision ID: d47403900116
Revises: dacbf8360781
Create Date: 2026-09-03 16:40:02.177194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd47403900116'
down_revision: Union[str, Sequence[str], None] = 'dacbf8360781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
priority_enum = postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='priority_enum')
status_enum = postgresql.ENUM(
    'TODO', 'IN_PROGRESS', 'DONE', name='status_enum')


def upgrade() -> None:
    # 1. Tworzymy nowe typy ENUM w PostgreSQL
    priority_enum.create(op.get_bind(), checkfirst=True)
    status_enum.create(op.get_bind(), checkfirst=True)

    # --- Modyfikacja kolumny PRIORITY ---
    # a) Usuwamy stary server default
    op.alter_column('tasks', 'priority', server_default=None)
    # b) Zmieniamy typ kolumny z jawną konwersją przez text
    op.alter_column(
        'tasks',
        'priority',
        type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', name='priority_enum'),
        existing_nullable=False,
        postgresql_using="priority::text::priority_enum"
    )
    # c) Ustawiamy nowy server default dopasowany do nowego enuma
    op.alter_column('tasks', 'priority',
                    server_default=sa.text("'LOW'::priority_enum"))

    # --- Modyfikacja kolumny STATUS ---
    # a) Usuwamy stary server default
    op.alter_column('tasks', 'status', server_default=None)
    # b) Zmieniamy typ kolumny
    op.alter_column(
        'tasks',
        'status',
        type_=sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='status_enum'),
        existing_nullable=False,
        postgresql_using="status::text::status_enum"
    )
    # c) Ustawiamy nowy server default
    op.alter_column('tasks', 'status',
                    server_default=sa.text("'TODO'::status_enum"))

    # --- Triggery PL/pgSQL ---
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ language 'plpgsql';
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # --- ADD TRIGGER REMOVAL HERE (MANUALLY) ---
    op.execute("DROP TRIGGER IF EXISTS update_tasks_updated_at ON tasks;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
                    existing_type=sa.Enum(
                        'TODO', 'IN_PROGRESS', 'DONE', name='status_enum'),
                    type_=postgresql.ENUM(
                        'TODO', 'IN_PROGRESS', 'DONE', name='statusenum'),
                    existing_nullable=False,
                    existing_server_default=sa.text("'TODO'::statusenum"))
    op.alter_column('tasks', 'priority',
                    existing_type=sa.Enum(
                        'LOW', 'MEDIUM', 'HIGH', name='priority_enum'),
                    type_=postgresql.ENUM(
                        'LOW', 'MEDIUM', 'HIGH', name='priorityenum'),
                    existing_nullable=False,
                    existing_server_default=sa.text("'LOW'::priorityenum"))
    priority_enum.drop(op.get_bind(), checkfirst=True)
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
