"""Initial tables creation

Revision ID: dacbf8360781
Revises: 
Create Date: 2026-09-03 12:25:02.530312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacbf8360781'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(
                        length=1000), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('tasks',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(
                        length=1000), nullable=True),
                    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH',
                                                  name='priorityenum'), server_default='LOW', nullable=False),
                    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE',
                                                name='statusenum'), server_default='TODO', nullable=False),
                    sa.Column('due_date', sa.Date(), nullable=True),
                    sa.Column('completed_at', sa.DateTime(
                        timezone=True), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('project_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['project_id'], ['projects.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###
    # 1. Create a generic PL/pgSQL function to update the updated_at field
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ language 'plpgsql';
    """)

    # 2. Create a trigger on the projects table
    op.execute("""
        CREATE TRIGGER update_projects_updated_at
        BEFORE UPDATE ON projects
        FOR EACH ROW
        EXECUTE PROCEDURE update_updated_at_column();
    """)
    op.execute("""
            CREATE TRIGGER update_tasks_updated_at
            BEFORE UPDATE ON tasks
            FOR EACH ROW
            EXECUTE PROCEDURE update_updated_at_column();
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # --- ADD TRIGGER REMOVAL HERE (MANUALLY) ---
    op.execute("DROP TRIGGER IF EXISTS update_projects_updated_at ON projects;")
    op.execute("DROP TRIGGER IF EXISTS update_tasks_updated_at ON tasks;")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('projects')
    # ### end Alembic commands ###
